# Tạo đề Tin học THPT 50 câu - có code HTML, Python, C++
from docx import Document
from docx.shared import Pt
from docx.enum.style import WD_STYLE_TYPE

doc = Document()
doc.styles['Normal'].font.name = 'Times New Roman'
doc.styles['Normal'].font.size = Pt(12)

_code_lines = []  # buffer dòng code hiện tại

def code(text):
    """Gom các dòng code, flush khi gặp q() hoặc blank()"""
    _code_lines.append(text)

def _flush_code():
    """Tạo paragraphs [CODE]...[/CODE] bao quanh block code"""
    if not _code_lines:
        return
    doc.add_paragraph('[CODE]')
    for line in _code_lines:
        doc.add_paragraph(line)
    doc.add_paragraph('[/CODE]')
    _code_lines.clear()

def q(text):
    _flush_code()
    doc.add_paragraph(text)

def blank():
    _flush_code()
    doc.add_paragraph('')

def th(text):
    _flush_code()
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(13)

th('ĐỀ THI THỬ TỐT NGHIỆP THPT QUỐC GIA MÔN TIN HỌC')
th('Thời gian làm bài: 50 phút (50 câu trắc nghiệm)')
blank()

# ===== PHẦN I: CẤU TRÚC DỮ LIỆU VÀ GIẢI THUẬT =====
th('PHẦN I. CẤU TRÚC DỮ LIỆU VÀ GIẢI THUẬT (Câu 1-10)')
blank()

q('Câu 1. Độ phức tạp thời gian của thuật toán sắp xếp nổi bọt (Bubble Sort) trong trường hợp xấu nhất là:')
q('A. O(n)')
q('B. O(n log n)')
q('C. O(n²) *')
q('D. O(log n)')
blank()

q('Câu 2. Cấu trúc dữ liệu nào hoạt động theo nguyên tắc LIFO (Last In First Out)?')
q('A. Queue (Hàng đợi)')
q('B. Stack (Ngăn xếp) *')
q('C. Linked List')
q('D. Tree')
blank()

q('Câu 3. Xét đoạn code C++ sau, kết quả in ra màn hình là:')
code('#include <iostream>')
code('using namespace std;')
code('int main() {')
code('    int a[] = {5, 3, 8, 1, 9, 2};')
code('    int n = 6, min = a[0];')
code('    for (int i = 1; i < n; i++)')
code('        if (a[i] < min) min = a[i];')
code('    cout << min;')
code('    return 0;')
code('}')
q('A. 5')
q('B. 9')
q('C. 1 *')
q('D. 2')
blank()

q('Câu 4. Thuật toán tìm kiếm nhị phân (Binary Search) yêu cầu mảng phải:')
q('A. Có số phần tử chẵn')
q('B. Đã được sắp xếp *')
q('C. Chứa các số nguyên')
q('D. Có độ dài cố định')
blank()

q('Câu 5. Xét hàm Python sau:')
code('def tinh(n):')
code('    if n <= 1:')
code('        return n')
code('    return tinh(n-1) + tinh(n-2)')
q('Gọi tinh(6) trả về giá trị:')
q('A. 6')
q('B. 8 *')
q('C. 10')
q('D. 12')
blank()

q('Câu 6. Trong cây nhị phân tìm kiếm (BST), phép duyệt Inorder cho kết quả:')
q('A. Các nút theo thứ tự tăng dần *')
q('B. Các nút theo thứ tự giảm dần')
q('C. Nút gốc trước, con trái, con phải')
q('D. Con trái, con phải, nút gốc')
blank()

q('Câu 7. Xét đoạn code Python sau:')
code('lst = [1, 2, 3, 4, 5]')
code('print(lst[1:4])')
q('Kết quả in ra là:')
q('A. [1, 2, 3]')
q('B. [2, 3, 4] *')
q('C. [2, 3, 4, 5]')
q('D. [1, 2, 3, 4]')
blank()

q('Câu 8. Độ phức tạp thời gian của thuật toán tìm kiếm nhị phân là:')
q('A. O(1)')
q('B. O(n)')
q('C. O(log n) *')
q('D. O(n²)')
blank()

q('Câu 9. Xét đoạn code C++ sau:')
code('int dem = 0;')
code('for (int i = 1; i <= 100; i++)')
code('    if (i % 3 == 0 && i % 5 == 0)')
code('        dem++;')
code('cout << dem;')
q('Kết quả in ra là:')
q('A. 3')
q('B. 6 *')
q('C. 7')
q('D. 10')
blank()

q('Câu 10. Hàng đợi (Queue) sử dụng nguyên tắc:')
q('A. LIFO - Last In First Out')
q('B. FIFO - First In First Out *')
q('C. Random Access')
q('D. Priority Based')
blank()

# ===== PHẦN II: LẬP TRÌNH C++ =====
th('PHẦN II. LẬP TRÌNH C++ (Câu 11-20)')
blank()

q('Câu 11. Đoạn code C++ sau in ra giá trị gì?')
code('#include <iostream>')
code('using namespace std;')
code('int f(int n) {')
code('    if (n == 0) return 1;')
code('    return n * f(n - 1);')
code('}')
code('int main() {')
code('    cout << f(5);')
code('}')
q('A. 24')
q('B. 120 *')
q('C. 60')
q('D. 720')
blank()

q('Câu 12. Trong C++, khai báo nào sau đây tạo mảng động đúng cú pháp?')
q('A. int arr[n]; (n là biến)')
q('B. int* arr = new int[n]; *')
q('C. int arr = new int[n];')
q('D. int[] arr = new int[n];')
blank()

q('Câu 13. Xét đoạn code C++:')
code('vector<int> v = {3, 1, 4, 1, 5, 9, 2, 6};')
code('sort(v.begin(), v.end());')
code('cout << v[3];')
q('Kết quả là:')
q('A. 1')
q('B. 3')
q('C. 4 *')
q('D. 5')
blank()

q('Câu 14. Hàm nào sau đây trong C++ dùng để tìm phần tử lớn nhất trong vector?')
q('A. max(v.begin(), v.end())')
q('B. *max_element(v.begin(), v.end()) *')
q('C. v.max()')
q('D. find_max(v)')
blank()

q('Câu 15. Xét đoạn code C++ sau:')
code('string s = "Hello World";')
code('cout << s.substr(6, 5);')
q('Kết quả in ra là:')
q('A. "Hello"')
q('B. "World" *')
q('C. "lo Wo"')
q('D. " Worl"')
blank()

q('Câu 16. Trong C++, con trỏ (pointer) được khai báo như thế nào?')
q('A. int &p;')
q('B. int *p; *')
q('C. pointer int p;')
q('D. ref int p;')
blank()

q('Câu 17. Đoạn code C++ sau có bao nhiêu lần in "Tin"?')
code('for (int i = 0; i < 4; i++)')
code('    for (int j = i; j < 4; j++)')
code('        cout << "Tin" << endl;')
q('A. 8')
q('B. 10 *')
q('C. 12')
q('D. 16')
blank()

q('Câu 18. Câu lệnh nào dùng để đọc cả dòng có khoảng trắng trong C++?')
q('A. cin >> s;')
q('B. scanf("%s", s);')
q('C. getline(cin, s); *')
q('D. cin.read(s);')
blank()

q('Câu 19. Xét đoạn code C++ sau, output là gì?')
code('int x = 5;')
code('int& r = x;')
code('r = 10;')
code('cout << x;')
q('A. 5')
q('B. 10 *')
q('C. Lỗi biên dịch')
q('D. 0')
blank()

q('Câu 20. Trong C++, từ khóa nào dùng để khai báo hằng số?')
q('A. static')
q('B. const *')
q('C. final')
q('D. fixed')
blank()

# ===== PHẦN III: LẬP TRÌNH PYTHON =====
th('PHẦN III. LẬP TRÌNH PYTHON (Câu 21-32)')
blank()

q('Câu 21. Kết quả của đoạn code Python sau là gì?')
code('x = [1, 2, 3, 4, 5]')
code('print(sum(x[::2]))')
q('A. 6')
q('B. 9 *')
q('C. 12')
q('D. 15')
blank()

q('Câu 22. Trong Python, kiểu dữ liệu nào là bất biến (immutable)?')
q('A. list')
q('B. dict')
q('C. set')
q('D. tuple *')
blank()

q('Câu 23. Xét đoạn code Python:')
code('d = {"a": 1, "b": 2, "c": 3}')
code('print(sorted(d, key=d.get, reverse=True)[0])')
q('Kết quả là:')
q('A. "a"')
q('B. "b"')
q('C. "c" *')
q('D. 3')
blank()

q('Câu 24. Hàm Python nào sau đây trả về danh sách các cặp (index, value)?')
q('A. zip()')
q('B. enumerate() *')
q('C. map()')
q('D. filter()')
blank()

q('Câu 25. Xét đoạn code Python:')
code('result = [x**2 for x in range(1, 6) if x % 2 == 0]')
code('print(result)')
q('Kết quả là:')
q('A. [1, 4, 9, 16, 25]')
q('B. [4, 16] *')
q('C. [2, 4]')
q('D. [4, 8]')
blank()

q('Câu 26. Trong Python, decorator được ký hiệu bằng:')
q('A. #')
q('B. @  *')
q('C. $')
q('D. &')
blank()

q('Câu 27. Xét đoạn code Python sau:')
code('class Animal:')
code('    def __init__(self, name):')
code('        self.name = name')
code('    def speak(self):')
code('        return f"{self.name} says..."')
code('')
code('class Dog(Animal):')
code('    def speak(self):')
code('        return f"{self.name} says Woof!"')
code('')
code('d = Dog("Rex")')
code('print(d.speak())')
q('Kết quả là:')
q('A. "Animal says..."')
q('B. "Rex says..."')
q('C. "Rex says Woof!" *')
q('D. Lỗi')
blank()

q('Câu 28. Hàm lambda trong Python nào sau đây tính bình phương đúng cú pháp?')
q('A. lambda(x): x**2')
q('B. lambda x: x**2 *')
q('C. def lambda(x): return x**2')
q('D. lambda x => x**2')
blank()

q('Câu 29. Xét đoạn code Python:')
code('from collections import Counter')
code('s = "programming"')
code('c = Counter(s)')
code('print(c.most_common(1)[0][0])')
q('Kết quả là ký tự xuất hiện nhiều nhất:')
q('A. "p"')
q('B. "r"')
q('C. "g" *')
q('D. "m"')
blank()

q('Câu 30. Trong Python, cách đọc file văn bản đúng và an toàn nhất là:')
q('A. f = open("file.txt"); data = f.read()')
q('B. with open("file.txt", "r") as f: data = f.read() *')
q('C. data = read("file.txt")')
q('D. import file; data = file.read("file.txt")')
blank()

q('Câu 31. Xét code Python:')
code('def tong(*args):')
code('    return sum(args)')
code('print(tong(1, 2, 3, 4, 5))')
q('Kết quả là:')
q('A. 10')
q('B. 15 *')
q('C. Lỗi vì quá nhiều tham số')
q('D. (1, 2, 3, 4, 5)')
blank()

q('Câu 32. Module nào trong Python dùng để làm việc với dữ liệu JSON?')
q('A. xml')
q('B. csv')
q('C. json *')
q('D. data')
blank()

# ===== PHẦN IV: HTML VÀ WEB =====
th('PHẦN IV. HTML VÀ LẬP TRÌNH WEB (Câu 33-42)')
blank()

q('Câu 33. Xét đoạn HTML sau, thẻ nào tạo liên kết?')
code('<!DOCTYPE html>')
code('<html>')
code('  <body>')
code('    <a href="https://example.com">Click here</a>')
code('    <p>Hello World</p>')
code('  </body>')
code('</html>')
q('A. <p>')
q('B. <a> *')
q('C. <body>')
q('D. <html>')
blank()

q('Câu 34. Trong HTML, thuộc tính nào dùng để đặt tên cho input để nhận dữ liệu form?')
q('A. id')
q('B. class')
q('C. name *')
q('D. value')
blank()

q('Câu 35. Xét đoạn HTML/CSS sau:')
code('<style>')
code('  .box {')
code('    width: 100px;')
code('    padding: 20px;')
code('    border: 5px solid black;')
code('    box-sizing: border-box;')
code('  }')
code('</style>')
q('Chiều rộng thực của phần tử .box là:')
q('A. 100px *')
q('B. 150px')
q('C. 145px')
q('D. 170px')
blank()

q('Câu 36. Trong JavaScript, đoạn code sau in ra gì?')
code('<script>')
code('  let arr = [1, 2, 3, 4, 5];')
code('  let result = arr.filter(x => x % 2 === 0).map(x => x * 2);')
code('  console.log(result);')
code('</script>')
q('A. [1, 3, 5]')
q('B. [2, 4]')
q('C. [4, 8] *')
q('D. [2, 4, 6, 8, 10]')
blank()

q('Câu 37. Thẻ HTML nào dùng để tạo bảng?')
q('A. <grid>')
q('B. <table> *')
q('C. <matrix>')
q('D. <data>')
blank()

q('Câu 38. Trong CSS, thuộc tính nào dùng để căn giữa nội dung theo chiều ngang?')
q('A. align: center')
q('B. text-align: center *')
q('C. center: true')
q('D. margin: center')
blank()

q('Câu 39. Xét đoạn HTML sau:')
code('<form method="POST" action="/submit">')
code('  <input type="text" name="username" required>')
code('  <input type="password" name="password">')
code('  <button type="submit">Đăng nhập</button>')
code('</form>')
q('Thuộc tính "required" có tác dụng gì?')
q('A. Mã hóa dữ liệu trước khi gửi')
q('B. Bắt buộc người dùng phải điền vào trường đó *')
q('C. Đặt giá trị mặc định cho trường')
q('D. Ẩn trường input')
blank()

q('Câu 40. Trong JavaScript, phương thức nào dùng để chọn phần tử theo class?')
q('A. document.getElementById()')
q('B. document.getElementsByClassName() *')
q('C. document.getClass()')
q('D. document.findClass()')
blank()

q('Câu 41. Xét đoạn JavaScript sau:')
code('async function getData() {')
code('    const response = await fetch("/api/data");')
code('    const data = await response.json();')
code('    return data;')
code('}')
q('Từ khóa "await" có tác dụng gì?')
q('A. Tạm dừng vòng lặp')
q('B. Chờ Promise hoàn thành trước khi tiếp tục *')
q('C. Tạo luồng mới')
q('D. Xử lý lỗi')
blank()

q('Câu 42. Trong HTML5, thẻ nào dùng để nhúng video?')
q('A. <media>')
q('B. <movie>')
q('C. <video> *')
q('D. <stream>')
blank()

# ===== PHẦN V: CƠ SỞ DỮ LIỆU VÀ SQL =====
th('PHẦN V. CƠ SỞ DỮ LIỆU VÀ SQL (Câu 43-46)')
blank()

q('Câu 43. Câu lệnh SQL nào dùng để lấy tất cả học sinh có điểm >= 8 từ bảng HocSinh?')
code('SELECT * FROM HocSinh WHERE Diem >= 8;')
q('Câu lệnh trên là:')
q('A. Sai cú pháp')
q('B. Đúng và trả về tất cả HS có điểm >= 8 *')
q('C. Chỉ trả về cột Diem')
q('D. Xóa các bản ghi có điểm >= 8')
blank()

q('Câu 44. Trong SQL, lệnh nào dùng để đếm số bản ghi?')
q('A. SUM()')
q('B. COUNT() *')
q('C. TOTAL()')
q('D. NUMBER()')
blank()

q('Câu 45. Xét câu truy vấn SQL:')
code('SELECT LopHoc, AVG(Diem) as DiemTB')
code('FROM HocSinh')
code('GROUP BY LopHoc')
code('HAVING AVG(Diem) > 7;')
q('Câu truy vấn này trả về:')
q('A. Tất cả học sinh có điểm > 7')
q('B. Tên lớp và điểm trung bình của các lớp có ĐTB > 7 *')
q('C. Số học sinh trong mỗi lớp')
q('D. Học sinh có điểm cao nhất trong mỗi lớp')
blank()

q('Câu 46. Khóa ngoại (Foreign Key) trong cơ sở dữ liệu quan hệ dùng để:')
q('A. Xác định tính duy nhất của bản ghi')
q('B. Thiết lập mối quan hệ giữa hai bảng *')
q('C. Tăng tốc độ truy vấn')
q('D. Mã hóa dữ liệu')
blank()

# ===== PHẦN VI: CÂU HỎI TỔNG HỢP =====
th('PHẦN VI. CÂU HỎI TỔNG HỢP (Câu 47-50)')
blank()

q('Câu 47. [MULTI] Xét đoạn code Python sau:')
code('numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]')
code('result = list(filter(lambda x: x % 2 == 0, numbers))')
q('Các khẳng định nào sau đây đúng?')
q('A. result = [2, 4, 6, 8, 10] *')
q('B. filter() trả về một iterator, list() chuyển thành danh sách *')
q('C. lambda x: x % 2 == 0 kiểm tra số chẵn *')
q('D. Kết quả result có 5 phần tử *')
blank()

q('Câu 48. [MULTI] Xét đoạn HTML/JavaScript sau:')
code('<button id="btn">Click</button>')
code('<script>')
code('  document.getElementById("btn")')
code('    .addEventListener("click", function() {')
code('      alert("Hello!");')
code('    });')
code('</script>')
q('Các khẳng định nào đúng?')
q('A. Khi click nút sẽ hiện hộp thoại "Hello!" *')
q('B. getElementById tìm phần tử theo thuộc tính id *')
q('C. addEventListener gắn sự kiện click vào nút *')
q('D. Đây là ví dụ về xử lý sự kiện DOM *')
blank()

q('Câu 49. [DUNG/SAI] Xác định đúng/sai về thuật toán và cấu trúc dữ liệu:')
q('A. Độ phức tạp O(1) nghĩa là thời gian thực thi không phụ thuộc vào kích thước đầu vào. (đúng)')
q('B. Quick Sort luôn có độ phức tạp O(n log n) trong mọi trường hợp. (sai)')
q('C. Hash Table cho phép tìm kiếm trung bình O(1). (đúng)')
q('D. Đệ quy (Recursion) luôn hiệu quả hơn vòng lặp (Iteration). (sai)')
blank()

q('Câu 50. [DUNG/SAI] Xác định đúng/sai về lập trình Python:')
q('A. Python là ngôn ngữ thông dịch (interpreted language). (đúng)')
q('B. Trong Python, list và tuple đều có thể thay đổi sau khi tạo. (sai)')
q('C. Hàm range(5) tạo dãy số từ 0 đến 4. (đúng)')
q('D. Python hỗ trợ đa kế thừa (multiple inheritance). (đúng)')
blank()

_flush_code()
doc.save('data/de-tin-demo.docx')
print('OK: data/de-tin-demo.docx')
